services:
  fastapi-app:
    image: car-project
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID= "${AWS_ACCESS_KEY_ID}"
      - AWS_SECRET_ACCESS_KEY = "${AWS_SECRET_ACCESS_KEY}"
      - AWS_SESSION_TOKEN = "${AWS_SESSION_TOKEN}"
      - S3_BUCKET = "${S3_BUCKET}"
      - S3_DEFORMATION_OBJECT_NAME = "${S3_DEFORMATION_OBJECT_NAME}"
      - S3_CAR_PART_OBJECT_NAME = "${S3_CAR_PART_OBJECT_NAME}"
      - S3_CAR_DAMAGE_OBJECT_NAME q= "${S3_CAR_DAMAGE_OBJECT_NAME}"


